version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - redis
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  redis:
    image: redis:6.0
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
